language: python
services:
  - docker
install:
  - docker-compose up --build -d
jobs:
  include:
    - stage: test
      script:
      - docker-compose run scanner pytest
      - docker-compose run scanner flake8