language: python
services:
  - docker
install:
  - docker-compose up --build -d
jobs:
  include:
    - stage: test
      script:
      - docker-compose run scanner pytest
      - docker-compose run scanner flake8
    - stage: build and push
      script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-server
      - docker build -t zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-server
      - docker push zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER
      - docker push zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER
      - docker logout