language: minimal
services:
  - docker
jobs:
  include:
    - stage: test
      script:
      - docker-compose up --build -d
      - docker-compose run scanner pytest
      - docker-compose run scanner flake8
    - stage: build and push
      script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-server
      - docker push zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER
      - docker build -t zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-scanner
      - docker push zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER
      - docker logout
    - stage: deploy
      script:
      - echo ${SSH_PUBLIC_KEY} >> $HOME/.ssh/known_hosts
      - ssh ${DEPLOY_USER}@${DEPLOY_HOST} "/home/${DEPLOY_USER}/scripts/deploy.sh ${TRAVIS_BUILD_NUMBER} ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"