language: minimal
services:
  - docker
jobs:
  include:
    - stage: test
      script:
      - echo "GITHUB_API_KEY=$GITHUB_API_KEY" >> .env
      - echo "PIPEDRIVE_API_KEY=$PIPEDRIVE_API_KEY" >> .env
      - docker-compose up --build -d
      - docker-compose run scanner pytest
      - docker-compose run scanner flake8
      - docker-compose run scanner-server flake8
    - stage: build and push
      script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - docker build -t zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-server
      - docker push zicdamasta/gist-scanner:server-v$TRAVIS_BUILD_NUMBER
      - docker build -t zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER . -f Dockerfile-scanner
      - docker push zicdamasta/gist-scanner:scanner-v$TRAVIS_BUILD_NUMBER
      - docker logout
    - stage: deploy
      script:
      - echo "$SSH_KEY" > ~/.ssh/key
      - chmod 600 ~/.ssh/key
      - eval `ssh-agent -s`
      - ssh-add ~/.ssh/key
      - ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/key ${DEPLOY_USER}@${DEPLOY_HOST} "/home/${DEPLOY_USER}/scripts/deploy.sh ${TRAVIS_BUILD_NUMBER} ${DOCKER_USERNAME} ${DOCKER_PASSWORD}"