version: '3.1'

services:

  scanner-server:
    build:
        context: .
        dockerfile: Dockerfile-server
    image: gist-scanner-server
    ports:
      - "80:5000"
    container_name: gist-scanner-server
    volumes:
      - ./scanner/output/user:/server/api/user
    env_file:
      - .env.example
    entrypoint: ["python", "server.py"]
  scanner:
    build:
      context: .
      dockerfile: Dockerfile-scanner
    image: gist-scanner
    container_name: gist-scanner
    volumes:
      - ./scanner/output:/scanner/output
      - ./scanner/logs:/scanner/logs
    env_file:
      - .env.example
