FROM python:3.10-slim

WORKDIR /gist_scanner_server
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY server .

ENV PYTHONPATH "${PYTHONPATH}:/gist_scanner_server"

EXPOSE 5000

CMD python server.py
